P2P
extreal-dev/Extreal.Integration.Web.Common pull request #1
Opened 2023-07-27 12:50 UTC by kiyohome

# 何の変更を加えましたか？

# 何を確認しましたか?

## 実装

- [ ] Frameworkの誤った使い方にすぐに気づけるように、無効な引数や無効なメソッド呼び出しに対するチェックが入っていることを確認しました
- [ ] Framework実行時の動きが分かるように、ログ（Error/Warn/Info/Debug）を出力していることを確認しました
- [ ] 静的解析で問題が見つからないことを確認しました
- [ ] フレームワーク利用者が使うAPI（主にprivate以外）に C# ドキュメントを記述しました

## テスト

- [ ] 全ての自動テストが成功することを確認しました
- [ ] テストカバレッジが100%になることを確認しました
- [ ] サンプルがあるものはサンプルが動作することを確認しました

## 変更影響

- [ ] GuideのReleaseページに変更内容が追加されることを確認しました
- [ ] GuideのModuleページ（機能ページ）に変更が反映されることを確認しました
- [ ] GuideのLearningページに変更が反映されることを確認しました
- [ ] Sample Applicationに変更が反映されることを確認しました

# レビュアーへのメッセージ

2023-08-17 10:14 UTC, sus-taguchi-t requested changes

2023-08-17 10:14 UTC, sus-taguchi-t commented on Samples~/MVS/App/AppPresenter.cs
> +            => stageNavigator.ReplaceAsync(StageName.TestStage);
`Forget()` メソッドをチェインさせた方が良いと思います。

2023-08-17 10:14 UTC, sus-taguchi-t commented on Samples~/MVS/WebGLScripts.meta
> +fileFormatVersion: 2
`Sample` 中の `WebGLScripts` ディレクトリも `~` を末尾につけた方が良いと思いました。
サンプルを動かそうとして TypeScript をビルドすると `node_modules` ディレクトリに依存ライブラリがたくさん入ってきて、その後 Unity Editor を開くとそれに対するメタファイルが生成され、その上生成されている間は Unity Editor を操作できないためです。

2023-08-17 10:14 UTC, sus-taguchi-t commented on WebScripts~/README.md.meta
> +﻿fileFormatVersion: 2
`WebScripts~` ディレクトリ以下のメタファイルはすべて不要だと思います。

2023-08-17 10:14 UTC, sus-taguchi-t commented on WebScripts~/src/helper.ts
> +    dynCall_vii(funcPtr: Pointer, buf1: Pointer, buf2: Pointer): void;
宣言の仕方を他と揃えた方が良いと思います。

```typescript
type Module = {
    _malloc: (size: number) => Pointer;
};
```

2023-08-17 10:14 UTC, sus-taguchi-t commented on Samples~/MVS/Extreal.Integration.Web.Common.MVS.asmdef
> +        "Unity.Collections",
`Unity.Collections` は不要です。

2023-08-17 10:35 UTC, sus-taguchi-t requested changes

2023-08-17 10:35 UTC, sus-taguchi-t commented on WebScripts~/src/helper.ts
> + * Determines if it is an AsynFunction.
AsynFunction -> AsyncFunction

2023-08-24 06:29 UTC, mahaweilu commented on Samples~/MVS/App/AppPresenter.cs
> +            => stageNavigator.ReplaceAsync(StageName.TestStage);
対応しました！https://github.com/extreal-dev/Extreal.Integration.Web.Common/pull/1/commits/4fda660f5fed98931e4053bab0773451d083d675

2023-08-24 06:29 UTC, mahaweilu commented on WebScripts~/README.md.meta
> +﻿fileFormatVersion: 2
対応しましたhttps://github.com/extreal-dev/Extreal.Integration.Web.Common/pull/1/commits/6068aa74804f6b9835eb1e2b07d6295e207db596

2023-08-24 06:30 UTC, mahaweilu commented on WebScripts~/src/helper.ts
> +    dynCall_vii(funcPtr: Pointer, buf1: Pointer, buf2: Pointer): void;
指摘通り対応しましたhttps://github.com/extreal-dev/Extreal.Integration.Web.Common/pull/1/commits/d0b7b9d9cf848a77a7ed710ef0f35802e61f8ef2

2023-08-24 06:30 UTC, mahaweilu commented on Samples~/MVS/WebGLScripts.meta
> +fileFormatVersion: 2
指摘通り対応しましたhttps://github.com/extreal-dev/Extreal.Integration.Web.Common/pull/1/commits/a1d7f4af5c79b98853d7ae4b5e981715d6bb2b77

2023-08-24 06:31 UTC, mahaweilu commented on Samples~/MVS/Extreal.Integration.Web.Common.MVS.asmdef
> +        "Unity.Collections",
指摘通り対応しましたhttps://github.com/extreal-dev/Extreal.Integration.Web.Common/pull/1/commits/6bdf7921b2d98f3a2a64745b721c3ba6d9b03ec5

2023-08-24 06:31 UTC, mahaweilu commented on WebScripts~/src/helper.ts
> + * Determines if it is an AsynFunction.
指摘通り対応しましたhttps://github.com/extreal-dev/Extreal.Integration.Web.Common/pull/1/commits/0a723644558d6aa111b335758877205bdeabb30c

2023-08-31 02:40 UTC, sus-taguchi-t commented on Samples~/MVS/App/AppPresenter.cs
> +            => stageNavigator.ReplaceAsync(StageName.TestStage);
確認しました！

2023-08-31 02:41 UTC, sus-taguchi-t commented on Samples~/MVS/WebGLScripts.meta
> +fileFormatVersion: 2
併せて `WebGLScripts~` ディレクトリ以下のメタファイルはすべて削除した方が良いと思います。

2023-08-31 02:42 UTC, sus-taguchi-t commented on WebScripts~/README.md.meta
> +﻿fileFormatVersion: 2
併せて `WebGLScripts~` ディレクトリ以下のメタファイルはすべて削除した方が良いと思います。

2023-08-31 02:42 UTC, sus-taguchi-t commented on Samples~/MVS/WebGLScripts.meta
> +fileFormatVersion: 2
併せて `WebGLScripts~` ディレクトリ以下のメタファイルはすべて削除した方が良いと思います。

2023-08-31 02:44 UTC, sus-taguchi-t commented on WebScripts~/README.md.meta
> +﻿fileFormatVersion: 2
`src` ディレクトリ以下にまだメタファイルが残っています。

2023-08-31 02:45 UTC, sus-taguchi-t commented on WebScripts~/src/helper.ts
> +    dynCall_vii(funcPtr: Pointer, buf1: Pointer, buf2: Pointer): void;
`_malloc` だけでなく他の関数についても同様です。

2023-08-31 02:45 UTC, sus-taguchi-t commented on Samples~/MVS/Extreal.Integration.Web.Common.MVS.asmdef
> +        "Unity.Collections",
確認しました！

2023-08-31 02:45 UTC, sus-taguchi-t commented on WebScripts~/src/helper.ts
> + * Determines if it is an AsynFunction.
確認しました！

2023-09-04 00:34 UTC, mahaweilu commented on WebScripts~/README.md.meta
> +﻿fileFormatVersion: 2
fixed https://github.com/extreal-dev/Extreal.Integration.Web.Common/pull/1/commits/7cea403fbbadf9298927465c7e77989b870b0afd

2023-09-04 00:34 UTC, mahaweilu commented on WebScripts~/src/helper.ts
> +    dynCall_vii(funcPtr: Pointer, buf1: Pointer, buf2: Pointer): void;
fixed https://github.com/extreal-dev/Extreal.Integration.Web.Common/pull/1/commits/b63261b94523294ed7a48f1fb2aa0d48c6c79713

2023-09-04 00:35 UTC, mahaweilu commented on Samples~/MVS/WebGLScripts.meta
> +fileFormatVersion: 2
fixed https://github.com/extreal-dev/Extreal.Integration.Web.Common/pull/1/commits/7dde891b2dccc3ea83fdf33b407d1bc11795d992

2023-09-07 00:56 UTC, sus-taguchi-t commented on Samples~/MVS/WebGLScripts.meta
> +fileFormatVersion: 2
`src` ディレクトリ以下にまだメタファイルが残っています。

2023-09-07 00:57 UTC, sus-taguchi-t commented on WebScripts~/README.md.meta
> +﻿fileFormatVersion: 2
確認しました！

2023-09-07 00:57 UTC, sus-taguchi-t commented on WebScripts~/src/helper.ts
> +    dynCall_vii(funcPtr: Pointer, buf1: Pointer, buf2: Pointer): void;
確認しました！

2023-09-07 01:08 UTC, mahaweilu commented on Samples~/MVS/WebGLScripts.meta
> +fileFormatVersion: 2
fixed https://github.com/extreal-dev/Extreal.Integration.Web.Common/pull/1/commits/bb7703d942ea1db2ac6912f2a8b17f1931c0612b

2023-09-11 00:55 UTC, sus-taguchi-t commented on Samples~/MVS/WebGLScripts.meta
> +fileFormatVersion: 2
確認しました。

2023-09-11 00:55 UTC, sus-taguchi-t approved these changes

2023-09-11 00:55 UTC, merged