WebGLの動画が白くなる問題の修正
extreal-dev/Extreal.Integration.Web.Common pull request #11
Opened 2024-03-22 04:28 UTC by sus-yoshikane-t

# 何の変更を加えましたか？

- WebGLの動画が白くなるのを、シェーダーで補正して元の色味になるように修正しました。

# 何を確認しましたか?

## 実装

- [x] Frameworkの誤った使い方にすぐに気づけるように、無効な引数や無効なメソッド呼び出しに対するチェックが入っていることを確認しました
- [x] Framework実行時の動きが分かるように、ログ（Error/Warn/Info/Debug）を出力していることを確認しました
- [x] 静的解析で問題が見つからないことを確認しました
- [x] フレームワーク利用者が使うAPI（主にprivate以外）に C# ドキュメントを記述しました

## テスト

- [x] 全ての自動テストが成功することを確認しました
  - 自動テスト無し 
- [x] テストカバレッジが100%になることを確認しました
- [x] サンプルがあるものはサンプルが動作することを確認しました

## 変更影響

内部ロジックの修正のみのため以下は未確認

- [x] GuideのReleaseページに変更内容が追加されることを確認しました
- [x] GuideのModuleページ（機能ページ）に変更が反映されることを確認しました
- [x] GuideのLearningページに変更が反映されることを確認しました
- [x] Sample Applicationに変更が反映されることを確認しました

# レビュアーへのメッセージ

参考
- [【Unity】【C#】ガンマ(Gamma, sRGB) - リニア(Linear) 値の相互変換 - ヽ｜∵｜ゝ(Fantom) の 開発blog？](http://fantom1x.blog130.fc2.com/blog-entry-403.html#CS_Gamma_Linear_Convert_Fast_Cubic)
- [WebGLRenderingContext](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext)
  - helper.GLctxはWebGLRenderingContextを継承した[WebGL2RenderingContext](https://developer.mozilla.org/en-US/docs/Web/API/WebGL2RenderingContext)のインスタンスです
- C:\Program Files\Unity\Hub\Editor\\[Unity Editorバージョン(2022.3.7f1以降)]\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\lib\Video.js
- [WebGLの基本](https://webglfundamentals.org/webgl/lessons/ja/webgl-fundamentals.html)

2024-03-25 08:51 UTC, kiyohome requested changes

2024-03-25 08:51 UTC, kiyohome commented on WebScripts~/src/helper.ts
> +        if (s2lTexture === null || prevVideoHeight !== element.videoHeight || prevVideoWidth !== element.videoWidth) {
実装している内容について、テストケースを明示して欲しいのと、MVSでテストできる状態にして欲しいです。
今後のメンテナンス時にリグレッションテストをすぐにできるようにしましょう。

2024-04-01 02:07 UTC, sus-taguchi-t requested changes

2024-04-01 02:07 UTC, sus-taguchi-t commented on Runtime/Video/WebGLEVideoPlayer.cs
> +
`colorSpace` は 29 行目で一緒に渡して良いと思います。

2024-04-01 06:26 UTC, sus-yoshikane-t commented on WebScripts~/src/helper.ts
> +        if (s2lTexture === null || prevVideoHeight !== element.videoHeight || prevVideoWidth !== element.videoWidth) {
テストケースを追加しました。https://github.com/extreal-dev/Extreal.Integration.Web.Common/pull/11/commits/8a2df6f3b1a9869901bc0fb3a3d234be7339e1c5

また、色空間による分岐のみで問題なかったため当該の分岐は削除しました。https://github.com/extreal-dev/Extreal.Integration.Web.Common/pull/11/commits/1afb594262771e11fa3a0caebe0ba06931cc3f40
- 詳細：
  - そもそも分岐するしないに関わらず、分岐以降でelement.videoHeight等を使用していない
  - →Unityのコードを確認したところ、element.videoHeight等が変わった際にs2lTextureは再作成しておらず、Unityに返るテクスチャ(texture)の方を再作成していた
  - →Unityに返るテクスチャは手前で既にelement.videoWidth, element.videoHeightを使って動画のサイズで作成できているため分岐は不要

2024-04-01 06:27 UTC, sus-yoshikane-t commented on Runtime/Video/WebGLEVideoPlayer.cs
> +
修正しました。https://github.com/extreal-dev/Extreal.Integration.Web.Common/pull/11/commits/05023dad16ed7fa6d2f181dc2fde9c506a0480e7

2024-04-01 06:39 UTC, sus-taguchi-t commented on Runtime/Video/WebGLEVideoPlayer.cs
> +
確認しました。

2024-04-02 02:34 UTC, sus-yoshikane-t commented on WebScripts~/src/helper.ts
> +        if (s2lTexture === null || prevVideoHeight !== element.videoHeight || prevVideoWidth !== element.videoWidth) {
テストケースを修正しました。https://github.com/extreal-dev/Extreal.Integration.Web.Common/pull/11/commits/0853338dc629efd287e087e2a807e42f4d670e9e
番号付きリストがマークダウンではアルファベットになってしまったため、HTMLで数値になるようにしています。

2024-04-02 02:59 UTC, kiyohome approved these changes

2024-04-02 06:13 UTC, sus-taguchi-t approved these changes

2024-04-02 06:14 UTC, merged