WebGLでのビデオ再生をJavaScriptに委譲できるようにする
extreal-dev/Extreal.Integration.Web.Common pull request #9
Opened 2024-02-06 06:39 UTC by sus-taguchi-t

# 何の変更を加えましたか？

- WebGLでのビデオ再生をJavaScriptに委譲できるようにしました
  - プラットフォームに応じてVideoPlayerを扱うクラスEVideoPlayerを作成しました
  - 動画を扱うときにJavaScriptで使用するヘルパー関数GL、GLctxをjslibファイルに追加しました

# 何を確認しましたか?

## 実装

- [ ] Frameworkの誤った使い方にすぐに気づけるように、無効な引数や無効なメソッド呼び出しに対するチェックが入っていることを確認しました
- [x] Framework実行時の動きが分かるように、ログ（Error/Warn/Info/Debug）を出力していることを確認しました
- [ ] 静的解析で問題が見つからないことを確認しました
- [ ] フレームワーク利用者が使うAPI（主にprivate以外）に C# ドキュメントを記述しました

## テスト

- [ ] 全ての自動テストが成功することを確認しました 
- [x] テストカバレッジが100%になることを確認しました
- [x] サンプルがあるものはサンプルが動作することを確認しました

## 変更影響

- [x] GuideのReleaseページに変更内容が追加されることを確認しました
- [x] GuideのModuleページ（機能ページ）に変更が反映されることを確認しました
- [x] GuideのLearningページに変更が反映されることを確認しました
    - 影響なし
- [x] Sample Applicationに変更が反映されることを確認しました
    - 影響なし 

# レビュアーへのメッセージ

- 名前空間およびクラス名で悩んでいるので良い命名があれば教えて欲しいです
  - どちらも VideoPlayer だと Unity の VideoPlayer と衝突してコーディングが大変になります

2024-02-20 10:26 UTC, kiyohome requested changes

2024-02-20 10:26 UTC, kiyohome commented on Runtime/Video/IVideoPlayer.cs
> +    public interface IVideoPlayer : IDisposable
インタフェースにせず、処理が共通化できるとこはまとめてよくないでしょうか？

2024-02-20 10:26 UTC, kiyohome commented on Runtime/Video/IVideoPlayer.cs
> +    public interface IVideoPlayer : IDisposable
ドキュメンテーションコメントは付けないですか？

2024-02-20 10:26 UTC, kiyohome commented on WebScripts~/src/Video/VideoPlayerAdopter.ts
> +class VideoPlayerAdopter {
Adopter -> Adapterでは？

2024-02-20 10:26 UTC, kiyohome commented on WebScripts~/src/index.ts
> +export * from "./Video/VideoPlayer";
Videoディレクトリに入れなくてもよくないでしょうか？

2024-02-20 10:26 UTC, kiyohome commented on WebScripts~/src/Video/VideoPlayerAdopter.ts
> +  public adopt = () => {
adopt　->　adaptでは？

2024-02-22 05:47 UTC, sus-yoshikane-t commented on WebScripts~/src/Video/VideoPlayerAdopter.ts
> +class VideoPlayerAdopter {
修正しました。https://github.com/extreal-dev/Extreal.Integration.Web.Common/pull/9/commits/c709f0e7c5c053019ec8b6ce047cd1c44bba7978

2024-02-22 05:47 UTC, sus-yoshikane-t commented on WebScripts~/src/Video/VideoPlayerAdopter.ts
> +  public adopt = () => {
修正しました。https://github.com/extreal-dev/Extreal.Integration.Web.Common/pull/9/commits/c709f0e7c5c053019ec8b6ce047cd1c44bba7978

2024-02-22 05:51 UTC, sus-yoshikane-t commented on Runtime/Video/IVideoPlayer.cs
> +    public interface IVideoPlayer : IDisposable
修正しました。https://github.com/extreal-dev/Extreal.Integration.Web.Common/pull/9/commits/3d9c5b4afe757b63d9ff95c3f3fac6954609f4e4

2024-02-22 05:54 UTC, sus-yoshikane-t commented on Runtime/Video/IVideoPlayer.cs
> +    public interface IVideoPlayer : IDisposable
他のライブラリと同様の形（ベースクラス、Nativeクラス、WebGLクラス、Providerクラス）に修正した際にIVideoPlayerインターフェースが無くなりました。https://github.com/extreal-dev/Extreal.Integration.Web.Common/pull/9/commits/3d9c5b4afe757b63d9ff95c3f3fac6954609f4e4

2024-02-22 05:58 UTC, sus-yoshikane-t commented on WebScripts~/src/index.ts
> +export * from "./Video/VideoPlayer";
Native側のコードと同じディレクトリ構成にすることで、今後機能が増えた際の管理が楽になると考え、Videoディレクトリに入れています。（Native側のディレクトリを機能ごとに分けているのは[Core.Common](https://github.com/extreal-dev/Extreal.Core.Common/tree/main)と同様です。）

2024-02-22 06:42 UTC, kiyohome approved these changes

2024-02-22 08:58 UTC, merged